### PR TITLE
Add library status and type to E14

### PR DESCRIPTION
**Pull request by franciscave**
See #87.

### CODE REVIEW

**Review by mdovey — COMMENTED** [review]
There have been some additional work in the issue since this pull request. Are the changes still correct

**Comment by franciscave** [comment]
Yes, I suggested some clarifications of overlapping ranges, which need to be documented. I’ll do this.

**Comment by franciscave** [comment]
...and I'm also adding opening/closing times, which I thought I had already added but hadn't.

**Comment by mdovey** [comment]
I've updated the relevant schema files.

However, I have one question why is E14D08  called library-status and not library-statutory-status 

This isn't a problem at the moment, but in future we might want a field for a different type of status for libraries (and the codelist it refers to is library statutory status)

**Comment by franciscave** [comment]
What is the conflict here?

**Comment by franciscave** [comment]
I've changed 'library-status' to 'library-statutory-status' in the XML binding spec.

**Comment by mdovey** [comment]
The conflict is merging the edits in lcf-v1.0-entities.xsd with the upstream change to this file to add a abstract entity base type in pul request #225. I can handle this.

**Comment by mdovey** [comment]
This pull request includes the opening\closing time structures which we discussed on today's Technical Panel meeting. 

This pull request is on hold until we have reworked the structures to address the issues raised.

**Review by mdovey — CHANGES_REQUESTED** [review]
Pending changes on the opening periods

**Comment by franciscave** [comment]
Data Framework, XML binding specifications and code value WKD00 updated to reflect changes in E14C04.3.

**Review by mdovey — APPROVED** [review]

**Pull request merged**
