### PR TITLE
Changes to cardinalities of response elements

### PR DESCRIPTION
**Pull request by franciscave**
See issue #226. Cardinalities of elements not implemented in REST have been changed from '1' (mandatory) to '0-1' (non-mandatory). This affects the responses in functions 3, 4, 5, 13, 14, 15.

### CODE REVIEW

**Review by mdovey — DISMISSED** [review]

**Comment by mdovey** [comment]
I've updated the schema and REST descriptions for lcf-check-out-response and lcf-check-in-response.

@franciscave Could you just sanity check these changes

**Review by franciscave — COMMENTED** [review]
In the REST Web Service Specification the element 'loan' should have element reference 'R12C09' - it's an entirely new element in the Data Framework - not 'R12D02', which is a reference to the old data element 'loan-ref'. We will need to add 'R12C09' to the Data Framework. I'm happy to do this, but equally happy for you to do so.

**Comment by mdovey** [comment]
I'll let you do the edits, then I can review and merge.

**Comment by franciscave** [comment]
Done.

**Review by mdovey — APPROVED** [review]

**Pull request merged**
